version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  MONGODB_USER=user1
      -  MONGODB_PASS=password
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles 
  mongo-express:
    container_name: mongo-express
    links:
      - mongodb:mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=user1
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    image: mongo-express
  wcdi-userstore:
    image: golang:1.10
    links:
      - mongodb:mongo
    ports:
      - 8080:8080
    command: go run /go/src/app/main.go server start
    volumes:
      - ./:/go/src/app

volumes:
  mongodb-data: {}
